# Generated by Django 5.1.1 on 2024-10-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loja", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="detalhe",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
